parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  TimeTracker\Infrastructure\Api\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Kernel.php"

  TimeTracker\Infrastructure\Api\Controller\:
    resource: "../src/Controller/"
    tags: ['controller.service_arguments']

  # Wire
  TimeTracker\Shared\:
    resource: "../../../../src/Shared"
