doctrine:
  dbal:
    default_connection: postgres
    connections:
      postgres:
        dbname: "%env(resolve:DATABASE_NAME)%"
        host: "%env(resolve:DATABASE_HOST)%"
        port: "%env(resolve:DATABASE_PORT)%"
        user: "%env(resolve:DATABASE_USER)%"
        password: "%env(resolve:DATABASE_PASSWORD)%"
        server_version: "%env(resolve:DATABASE_SERVER_VERSION)%"
        charset: "%env(resolve:DATABASE_CHARSET)%"
        driver: "%env(resolve:DATABASE_DRIVER)%"
    types:
      uuid: App\Shared\Infrastructure\Persistence\Doctrine\Type\UuidType

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      User:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Users/Infrastructure/Persistence/Doctrine/mappings'
        prefix: 'App\Users\Domain'
        alias: App\Users\Domain
        type: xml
      WorkEntry:
        is_bundle: false
        dir: '%kernel.project_dir%/src/WorkEntries/Infrastructure/Persistence/Doctrine/mappings'
        prefix: 'App\WorkEntries\Domain'
        alias: App\WorkEntries\Domain
        type: xml
    filters:
      softdeleteable:
        class: App\Shared\Infrastructure\Persistence\Doctrine\Filter\SoftDeleteableFilter
        enabled: true

when@test:
  doctrine:
    dbal:
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
