work_entries_get:
  path: /work_entries
  controller: App\UI\Controller\WorkEntries\GetWorkEntriesController
  methods: GET
  requirements:
    userId: '%routing.uuid%'

work_entries_get_by_id:
  path: /work_entries/{id}
  controller: App\UI\Controller\WorkEntries\GetWorkEntryByIdController
  methods: GET
  requirements:
    id: '%routing.uuid%'

work_entries_create:
  path: /work_entries
  controller: App\UI\Controller\WorkEntries\CreateWorkEntryController
  methods: POST

work_entries_update:
  path: /work_entries
  controller: App\UI\Controller\WorkEntries\UpdateWorkEntryController
  methods: PUT

work_entries_delete:
  path: /work_entries/{id}
  controller: App\UI\Controller\WorkEntries\DeleteWorkEntryByIdController
  methods: DELETE
  requirements:
    id: '%routing.uuid%'
