# FAVICON (avoid console error)
favicon:
    path: /favicon.ico
    controller:
    methods: GET

# USERS
users:
    resource: routes/users.yaml
    prefix: /api/

# WORK ENTRIES
work_entries:
    resource: routes/work_entries.yaml
    prefix: /api/
