# FAVICON (avoid console error)
favicon:
  path: /favicon.ico
  controller:
  methods: GET

# USERS
users_get_all:
    path: /users
    controller: App\UI\Controller\Users\GetUsersController
    methods: GET

users_get:
    path: /users/{id}
    controller: App\UI\Controller\Users\GetUserByIdController
    methods: GET
    requirements:
        id: '%routing.uuid%'

users_create:
    path: /users
    controller: App\UI\Controller\Users\CreateUserController
    methods: POST

users_update:
    path: /users
    controller: App\UI\Controller\Users\UpdateUserController
    methods: PUT

# WORK ENTRIES
