parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  TimeTracker\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Kernel.php"

  TimeTracker\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]

  # Wire
  App\Shared\:
    resource: "../../../src/Shared"
